<?php

namespace Database\Seeders;

use App\Models\Pelatihan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PelatihanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            "PM HD 465-7",
            "PM & PK BARGE LOADER & CRUSHER",
            "PM VOLVO A 40D",
            "PM TAMROCK",
            "PM PC 750-7",
            "PM GD 705-4",
            "AC",
            "PM PC 2000-8",
            "PM NISSAN TZA 520",
            "PM HD 785-7",
            "PM & PK GENSET/ LIGHTING",
            "PK PC 2000-8",
            "PM SCANIA P 360/P 380/P 410",
            "PM D 245S",
            "PM GENSET/LIGHTING",
            "PK PC 750-7",
            "PK PC 1250-8",
            "PM & PK PC 1250-8",
            "PM PC 1250-8",
            "AC, AUTOLUBE, FIRE SUPPRESSION",
            "PM & PK SCANIA P 360/P 380/P 410",
            "PK HD 465-7",
            "PK D 375-5",
            "PM D 375-5",
            "ECS & HCS HD 465-7",
            "ECS & HCS PC 750-7",
            "PM WA 600-3",
            "ECS BARGE LOADER & CRUSHER",
            "PK WA 600-3",
            "ECS & HCS SCANIA SCANIA P 360/P 380/P 410",
            "PM GD 825A-2",
            "PK GD 825-2",
            "ECS & HCS GD 705-4",
            "PK GD 705-4",
            "FIRE SUPPRESSION",
            "PM MANITOU",
            "MTS PC 1250-8",
            "AUTOLUBE",
            "ECS GENSET/LIGHTING",
            "MTS GENSET/LIGHTING",
            "ECS & HCS PC 2000-8",
            "AFA",
            "ECS & HCS PC 1250-8",
            "MTS WA 600-3",
            "ET INTRODUCTION",
            "HEEM",
            "ECS & HCS D 375-5",
            "PK HD 785-7",
            "MTS BARGE LOADER & CRUSHER",
            "PM FORKLIFT FD50",
            "PK FORKLIFT FD50",
            "ECS & HCS HD 785-7",
            "MTS HD 785-7",
            "PM NISSAN CWB 45",
            "MTS HD 465-7",
            "PM BW 216",
            "MTS GD 511",
            "PK GENSET/LIGHTING",
            "AC, AUTOLUBE",
            "PK NISSAN CWB 45",
            "PM D 155-2",
            "PK SCANIA P 360/P 380/P 410",
            "MTS SCANIA P 360/P 380/P 410",
            "PK D 245S",
            "MTS GD 825-2",
            "ENGINE CAT",
            "PM VOLVO FM",
            "PK VOLVO FM",
            "PM PC 200/300/400",
            "PK PC 200/300/400",
            "PK FORKFLIFT FD50",
            "PM FORKFLIFT FD50",
            "PK MANITOU",
            "MTS GD 705-4",
            "MTS D 375-5",
            "ADVANCE ELECTRIC",
            "MTS VOLVO FM",
            "MTS D 245S",
            "GMC PC 2000-8",
            "PM MF 420",
            "PK MF 420",
            "PM & PK TRAILLER",
            "HOT SPLICING",
            "PK BARGE LOADER",
            "KMMS",
            "K3 LISTRIK",
            "PM BARGE LOADER & CRUSHER",
            "PK BARGE LOADER & CRUSHER",
            "MTS MF 420",
            "HEEM & PDU",
            "PM TADANO GR 500EXL",
            "MTS PC 200/300/400",
            "PK PC 850-8",
            "FOWAG",
            "PM D 375-6",
            "MTS D 375-6",
            "BELT CONVEYOR",
            "PM GD 705-5",
            "PM PC 850-8",
            "PM VOLVO FH 16",
            "PK VOLVO FH 16",
            "HEEM & HEHM",
            "PK D 375-6",
            "PM & PK CRUSHER",
            "PM D 155-6",
            "PK D 155-6",
            "HOT-COLD SPLICING",
            "MEKATRONIKA",
            "PM TOWER LAMP",
            "MTS GD 705-5",
            "ELECTRICAL D 245",
            "PM PW R 140W-9S",
            "GMC PC 1250-8",
            "PK PW R 140W-9S",
            "PK GD 705-5",
            "MTS TADANO GR 500EXL",
            "COH TRANSMISSION SCANIA P 360/P 380/P 410",
            "MTS CRUSHER",
            "MTS SCANIA P 360/P 380/ P 410",
            "PK GD 705A-5",
            "MTS GD 705A-5",
            "PM WA 500-3",
            "PK FORKLIFT FD51",
            "PK FORKLIFT FD52",
            "MTS HD 465-8",
            "AIR CONDITIONER",
            "PM HD 785",
            "COH T/M SCANIA P 360/P 380/P 410",
            "PK PC 1250",
            "PM PW R 140W",
            "PK HD 785",
            "PM MF420",
            "PM D155",
            "MTS WA600-3",
            "COH T/M SCANIA P 360/ P 380/ P 410",
            "PM PC200/300/400",
            "PK HD785-7",
            "PM PC850",
            "PM WA600-3",
            "PK WA600-3",
            "MTS WA500-3",
            "MTS HD785-7",
            "MTS DZ375",
            "PK PC850",
            "PM PC1250",
            "MTS MF420",
            "ET TOOLS",
            "PM D245s",
            "PK D245s",
            "PK PC1250",
            "PK D155",
            "PK D 375",
            "PK PW140R",
            "PM HD785",
            "PM GENSET",
            "PK GENSET",
            "PM WA500",
            "MTS SCANIA P 360/P 410",
            "PM GD705-5",
            "PK GD705-5",
            "PK WA500",
            "MTS MF290",
            "PK HD785",
            "MTS WA 500",
            "MTS GD705",
            "MTS HD465-7",
            "PM PC1250-8",
            "PM SCANIA P 360/P 380/P 411",
            "PK WA500-3",
            "MTS PC1250-8",
            "PM GD825A-2",
            "PK D155-6",
            "PK GD825-2",
            "Advance Electric batch 1",
            "PK GD825",
            "PK GD705",
            "ELECTRIC BARGE LOADER & CRUSHER",
            "PM PK PC1250-11",
            "PM Tadani GR500EXL",
            "PK Tadani GR500EXL"
        ];

        foreach ($data as $value) {
            Pelatihan::create([
                'name' => $value,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
